/** 兼容层：新代码请 `import from "@changmen/api-contract"` */
export type {
  ApiEnvelope,
  BetRowDto,
  BetSourceDto,
  ChatMessageRow,
  ClientMatchDto,
  CollectPlatformInfo,
  LoginInfo,
  MoneyLogRow,
  ObGameOddTypeSpec,
  OrderRow,
  PageResult,
  PlatformId,
  PlayerOrderRow,
  TagPlatformRow,
  UserInfo,
  UserListRow,
  UserProfitRow,
} from "@changmen/api-contract";
