/** 管理端展示用：用户 setting 字段中文标签 */
export const ADMIN_SETTING_LABELS: Record<string, string> = {
  betting: "自动投注",
  bettingAutoOpen: "定时开启投注",
  bettingAutoOpenTime: "定时开启时间",
  betMoney: "投注金额",
  minMoney: "随机金额下限",
  maxMoney: "随机金额上限",
  tenNumber: "整十金额",
  makeUp: "补单",
  makeUp_odds: "补单赔率阈值",
  makeUp_defaultOdds: "补单默认赔率",
  makeProfit: "补单利润",
  noSameProvider: "禁止同平台",
  noSameBet: "禁止同盘口多账号",
  allowSameBet: "允许同盘口平台",
  anyOdds: "任意赔率",
  anyOddsProfit: "任意赔率利润",
  betSorting: "下注排序",
  winRateValue: "胜率权重",
  providerSortValue: "平台顺序",
  providerFixed: "固定平台",
  profit: "最低利润",
  maxProfit: "最高利润",
  minOdds: "最低赔率",
  maxOdds: "最高赔率",
  betCount: "最大下注次数",
  betInterval: "下注间隔(秒，A8 未用于调度；主循环约 100ms)",
  checkTimeout: "前置检查超时(ms)",
  betChecked: "仅已检查",
  singleBet: "单注模式",
  waitTime: "平台等待(秒)",
  BetTarget: "投注目标",
  Follow: "跟单",
  hiddenUserName: "隐藏用户名",
  CollectConfig: "采集开关",
};

export const BET_SORTING_LABELS: Record<string, string> = {
  Low: "低赔优先",
  High: "高赔优先",
  Parallel: "并行投注",
  WinRate: "胜率优先",
  Custom: "自定义顺序",
};
