-- 充提流水（account_store / report_service / impl_rds.js）
--
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/migrations/003_money_logs.sql
--
-- 幂等：IF NOT EXISTS，可重复执行。

BEGIN;

CREATE TABLE IF NOT EXISTS money_logs (
  id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id     uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  player_id   bigint NOT NULL,
  type        text NOT NULL DEFAULT 'Recharge',
  money       double precision NOT NULL DEFAULT 0,
  currency    text NOT NULL DEFAULT 'CNY',
  description text NOT NULL DEFAULT '',
  is_auto     smallint NOT NULL DEFAULT 0,
  create_at   bigint NOT NULL,
  updated_at  bigint NOT NULL
);

CREATE INDEX IF NOT EXISTS money_logs_user_player
  ON money_logs(user_id, player_id);

CREATE INDEX IF NOT EXISTS money_logs_create_at
  ON money_logs(create_at);

COMMIT;
