-- 信用盘 tag_platforms / players（原 storage/*.json，account_store / impl_rds.js）
--
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/migrations/006_tag_platforms_players.sql
--
-- 幂等：IF NOT EXISTS，可重复执行。

BEGIN;

CREATE TABLE IF NOT EXISTS tag_platforms (
  id         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name       text NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS tag_platforms_name
  ON tag_platforms (name);

CREATE TABLE IF NOT EXISTS players (
  id                 bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  platform_id        bigint NOT NULL REFERENCES tag_platforms(id),
  platform_name      text NOT NULL DEFAULT '',
  player_name        text NOT NULL DEFAULT '',
  credit             double precision NOT NULL DEFAULT 0,
  total_balance      double precision NOT NULL DEFAULT 0,
  created_at         bigint NOT NULL,
  updated_at         bigint NOT NULL,
  deleted_at         bigint,
  delete_description text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS players_platform_id
  ON players (platform_id);

CREATE INDEX IF NOT EXISTS players_active
  ON players (id)
  WHERE deleted_at IS NULL;

COMMIT;
