-- 客户端诊断日志（Client_SaveUserLog / A8 Vt.saveLog）
--
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/migrations/008_user_logs.sql
--
-- 幂等：IF NOT EXISTS，可重复执行。

BEGIN;

CREATE TABLE IF NOT EXISTS user_logs (
  id        bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id   uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title     text NOT NULL DEFAULT '',
  data      text NOT NULL DEFAULT '',
  create_at bigint NOT NULL
);

CREATE INDEX IF NOT EXISTS user_logs_user_create
  ON user_logs (user_id, create_at DESC);

COMMIT;
